algoritmo "maior e menor"
// Função :
// Autor :
// Data : 3/11/2011
// Seção de Declarações 
var
n1,n2,n3:inteiro

inicio
// Seção de Comandos 
escreval("digite o 1° numero inteiro")
leia(n1)
escreval("digite o 2° numero inteiro")
leia(n2)
escreval("digite o 3° numero inteiro")
leia(n3)
se(n1 > n2) e (n1 > n3) entao
  escreval("o maior é ",n1)
senao
se(n2 > n1) e (n2 > n3)entao
  escreval("o maior é ",n2)
senao
  escreval("o maior é ",n3)
fimse
fimse
fimalgoritmo
